### ISSUE TITLE
Store Hot Wallet Address

### ISSUE THREAD

**Issue by xanderdunn** [numerai/contract#14]
Idea:
Create a hot_wallet variable.  hot_wallet can be changed.  `stakeOnBehalf` asserts that msg.sender is hot_wallet.  numeraiTransfer can transfer only to hot_wallet

Is this better than the current situation? 
Current Situation: Any owner can call `stakeOnBehalf` and give it an address from which to remove NMR from to make the stake.

**Comment by philipcmonk** [comment]
This would definitely be better than the current situation.  It eliminates the whole class of human errors where Numerai accidentally stakes with someone else's NMR.

**Comment by philipcmonk** [comment]
When we change the hot wallet, should we take the new address as an argument and require that the address not already have NMR?  Without the restriction that the address doesn't already have NMR, this is largely a cosmetic change, since a rogue owner would be able to just change the hot wallet to an already-existing address, and then siphon away a user's NMR.

Alternatively, changeHotWallet could change the wallet to msg.sender, ensuring that only the owner of an address can expose it to being the hot wallet.

**Comment by philipcmonk** [comment]
Superseded by #21
